/**
 * Payment ledger — append-only.
 *
 *   payments/{YYYY-MM-DD}/{uid}/{pushKey} -> StoredPayment
 *
 * Entries are never edited or deleted. A mistake is corrected by a REVERSAL:
 * a new entry with a negative amount, `reversalOf` naming the original and a
 * mandatory `reversalReason`. Security rules enforce create-only for everyone,
 * admins included.
 *
 * `totalPaid` on the batch is a CACHE, maintained by an atomic server-side
 * increment in the same multi-path update that writes the entry. The ledger is
 * the source of truth; where the two disagree, the sum of entries wins and the
 * cache is recalculated from it.
 *
 * WHY NOT UNDER THE BATCH: in RTDB a write permitted at an ancestor grants the
 * whole subtree, and admins may write the batch node — so nested payments could
 * be erased by a batch write with no create-only rule able to stop it. The day
 * bucket is also keyed by PAYMENT date, not sale date, so a payment taken today
 * against last month's invoice lands in today's drawer.
 */

import type { PaymentEntry, PaymentMethod, SalesBatch, StoredPayment } from '@/components/records/types';
import { dbService } from '@/services/db';
import { localDayKey } from '@/utils/date';
import { roundNaira } from '@/utils/money';

const PAYMENTS_ROOT = 'payments';

export interface PaymentActor {
  uid: string;
  name: string;
}

/* ------------------------------------------------------------------ *
 * Pure core — no I/O, so the risky parts are testable.
 * ------------------------------------------------------------------ */

export interface BuildPaymentInput {
  batch: Pick<SalesBatch, 'dbPath' | 'id' | 'receiptId'>;
  /** Naira. Rounded here; negative only for a reversal. */
  amount: number;
  method: PaymentMethod;
  actor: PaymentActor;
  /** Push key, generated by the caller so this stays pure. */
  key: string;
  note?: string;
  reversalOf?: string;
  reversalReason?: string;
  /** Injectable for tests. */
  now?: Date;
}

export interface PaymentWrite {
  dayKey: string;
  paymentPath: string;
  totalPaidPath: string;
  /**
   * Pointer index on the SALE: `sales/…/{saleId}/paymentRefs/{key}`.
   *
   * The ledger is bucketed by payment date, which makes Daily Cash a
   * single-day read but leaves "this sale's payments" a scan across every day.
   * This ref makes that lookup structural without moving the ledger.
   *
   * It is an INDEX, not a record. The entry under `payments/…` is the money;
   * this only says where to find it. If a ref is ever lost, it is rebuildable
   * from the ledger — see scripts/backfill-payment-refs.ts.
   */
  refPath: string;
  /** `{dayKey}/{uid}` — the ledger location, minus the shared key. */
  refValue: string;
  entry: StoredPayment;
  /** Whole naira; what `totalPaid` must move by. */
  delta: number;
}

/**
 * Build the atomic write for one payment.
 *
 * Returns BOTH paths that must move together. Applying only one of them leaves
 * the ledger and the cached total disagreeing permanently, which is why the
 * caller sends them in a single multi-path update rather than two writes.
 */
export function buildPaymentWrite(input: BuildPaymentInput): PaymentWrite {
  const now = input.now ?? new Date();
  const dayKey = localDayKey(now);
  const amount = roundNaira(input.amount);

  if (input.reversalOf && !input.reversalReason?.trim()) {
    throw new Error('A reversal must state a reason.');
  }
  if (!input.reversalOf && amount <= 0) {
    throw new Error('A payment must be greater than zero.');
  }

  const entry: StoredPayment = {
    amount,
    method: input.method,
    at: now.toISOString(),
    atMs: now.getTime(),
    byUid: input.actor.uid,
    byName: input.actor.name,
    receiptId: input.batch.receiptId ?? input.batch.id,
    batchPath: input.batch.dbPath,
    ...(input.note?.trim() ? { note: input.note.trim() } : {}),
    ...(input.reversalOf
      ? { reversalOf: input.reversalOf, reversalReason: input.reversalReason!.trim() }
      : {}),
  };

  // The ref reuses the entry's own key, so ref key === entry key and the two
  // can be reconciled by set comparison rather than by parsing values.
  const refValue = `${dayKey}/${input.actor.uid}`;

  return {
    dayKey,
    paymentPath: `${PAYMENTS_ROOT}/${dayKey}/${input.actor.uid}/${input.key}`,
    totalPaidPath: `${input.batch.dbPath}/totalPaid`,
    refPath: `${input.batch.dbPath}/paymentRefs/${input.key}`,
    refValue,
    entry,
    delta: amount,
  };
}

/** @internal Exported for unit tests. */
export function normalizePayment(
  raw: StoredPayment,
  id: string,
  dayKey: string,
  uid: string,
): PaymentEntry {
  return {
    id,
    dbPath: `${PAYMENTS_ROOT}/${dayKey}/${uid}/${id}`,
    dayKey,
    amount: roundNaira(raw.amount ?? 0),
    method: (raw.method ?? 'Cash') as PaymentMethod,
    at: raw.at ?? '',
    atMs: raw.atMs ?? 0,
    byUid: raw.byUid ?? uid,
    byName: raw.byName ?? 'Unknown',
    receiptId: raw.receiptId ?? '',
    batchPath: raw.batchPath ?? '',
    note: raw.note,
    reversalOf: raw.reversalOf,
    reversalReason: raw.reversalReason,
    isReversal: !!raw.reversalOf,
  };
}

/**
 * Parse the `payments` tree into a flat list, newest first.
 *
 * Tolerates a partial tree: a staff member can only read their own uid bucket,
 * so the shape they receive is `{ [day]: { [theirUid]: { … } } }`.
 *
 * @internal Exported for unit tests.
 */
export function parsePaymentsTree(root: any): PaymentEntry[] {
  if (!root || typeof root !== 'object') return [];
  const out: PaymentEntry[] = [];

  for (const [dayKey, byUid] of Object.entries(root)) {
    if (!byUid || typeof byUid !== 'object') continue;
    for (const [uid, entries] of Object.entries(byUid as Record<string, any>)) {
      if (!entries || typeof entries !== 'object') continue;
      for (const [id, raw] of Object.entries(entries as Record<string, any>)) {
        if (!raw || typeof raw !== 'object') continue;
        out.push(normalizePayment(raw as StoredPayment, id, dayKey, uid));
      }
    }
  }

  return out.sort((a, b) => b.atMs - a.atMs);
}

/* ------------------------------------------------------------------ *
 * Reads
 * ------------------------------------------------------------------ */

/**
 * Subscribe to the payment ledger.
 *
 * Kept separate from `subscribeToBatches` so Records and the Board do not pay
 * to fetch payments they never render.
 */
/**
 * One sale's payments, via its `paymentRefs` index.
 *
 * Replaces a subscription to the WHOLE ledger that filtered client-side to find
 * one sale's entries. Payments accumulate faster than sales, so that read
 * degraded sooner than anything else in the app.
 *
 * Subscribes to the ref map only, then fetches each entry once. Entries are
 * immutable — create-only by rule, corrected by reversal rather than edit — so
 * there is nothing to watch on them. The ref map is the only thing that changes
 * when a payment is added, and adding one re-runs this.
 */
export function subscribeToPaymentsForSale(
  batchPath: string,
  callback: (payments: PaymentEntry[]) => void,
): () => void {
  let cancelled = false;

  const unsubscribe = dbService.subscribe<Record<string, string>>(
    `${batchPath}/paymentRefs`,
    async (refs) => {
      if (!refs) {
        if (!cancelled) callback([]);
        return;
      }

      const entries = await Promise.all(
        Object.entries(refs).map(async ([key, location]) => {
          const node = await dbService.getRecord<StoredPayment>(
            `${PAYMENTS_ROOT}/${location}/${key}`,
          );
          if (!node) return null;
          const [dayKey, uid] = location.split('/');
          return normalizePayment(node, key, dayKey, uid);
        }),
      );

      if (cancelled) return;
      callback(
        entries
          .filter((e): e is PaymentEntry => e !== null)
          .sort((a, b) => b.atMs - a.atMs),
      );
    },
  );

  return () => {
    cancelled = true;
    unsubscribe();
  };
}

/**
 * Subscribe to a WINDOW of days, inclusive.
 *
 * Scoping an integrity check necessarily weakens it: a discrepancy outside the
 * window is not seen. That is inherent to scoping, not a flaw in it — so
 * anything built on this must SAY what period it covers rather than implying
 * the whole ledger agrees. Silence outside the window is the failure mode the
 * check exists to prevent, only quieter.
 */
export function subscribeToPaymentsInRange(
  startDayKey: string,
  endDayKey: string,
  callback: (payments: PaymentEntry[]) => void,
): () => void {
  return dbService.subscribeToKeyRange(PAYMENTS_ROOT, startDayKey, endDayKey, (root) =>
    callback(parsePaymentsTree(root)),
  );
}

/** Subscribe to a single day — what the reconciliation view needs. */
export function subscribeToPaymentsForDay(
  dayKey: string,
  callback: (payments: PaymentEntry[]) => void,
): () => void {
  return dbService.subscribe(`${PAYMENTS_ROOT}/${dayKey}`, (byUid) =>
    callback(parsePaymentsTree(byUid ? { [dayKey]: byUid } : null)),
  );
}

/* ------------------------------------------------------------------ *
 * Writes
 * ------------------------------------------------------------------ */

export interface RecordPaymentInput {
  batch: Pick<SalesBatch, 'dbPath' | 'id' | 'receiptId'>;
  amount: number;
  method: PaymentMethod;
  actor: PaymentActor;
  note?: string;
}

/**
 * Record a payment against a sale.
 *
 * The entry and the `totalPaid` increment go in ONE atomic multi-path update.
 * Two sequential writes could leave the ledger and the cache disagreeing
 * forever if the second failed.
 *
 * The increment is applied server-side, so two devices taking payments on the
 * same invoice both land — unlike the read-modify-write this replaces, where
 * the second write silently erased the first.
 */
export async function recordPayment(input: RecordPaymentInput): Promise<string> {
  const dayKey = localDayKey(new Date());
  const key = dbService.newKey(`${PAYMENTS_ROOT}/${dayKey}/${input.actor.uid}`);

  const write = buildPaymentWrite({ ...input, key });

  await dbService.updateAtomic({
    [write.paymentPath]: write.entry,
    [write.totalPaidPath]: dbService.increment(write.delta),
    [write.refPath]: write.refValue,
  });

  return key;
}

/**
 * Reverse a payment. Admin-only, enforced by the security rules.
 *
 * Writes a NEW entry with the negated amount rather than touching the original.
 * The original stays in the ledger forever — that is what makes the history
 * auditable rather than merely current.
 */
export async function reversePayment(
  original: PaymentEntry,
  reason: string,
  actor: PaymentActor,
): Promise<string> {
  if (!reason.trim()) throw new Error('A reversal must state a reason.');
  if (original.isReversal) throw new Error('A reversal cannot itself be reversed.');

  const dayKey = localDayKey(new Date());
  const key = dbService.newKey(`${PAYMENTS_ROOT}/${dayKey}/${actor.uid}`);

  const write = buildPaymentWrite({
    batch: {
      dbPath: original.batchPath,
      id: original.receiptId,
      receiptId: original.receiptId,
    },
    amount: -original.amount,
    method: original.method,
    actor,
    key,
    reversalOf: original.id,
    reversalReason: reason,
  });

  await dbService.updateAtomic({
    [write.paymentPath]: write.entry,
    [write.totalPaidPath]: dbService.increment(write.delta),
    [write.refPath]: write.refValue,
  });

  return key;
}

/**
 * Reset a batch's cached `totalPaid` to the sum of its ledger entries.
 *
 * The ONLY place `totalPaid` is written without an increment, and it only ever
 * writes what the ledger already says. Admin-only in the UI; it cannot invent
 * money, since its input is the entries themselves.
 */
export async function recalculateTotalPaid(
  batch: Pick<SalesBatch, 'dbPath'>,
  paymentsForBatch: PaymentEntry[],
): Promise<number> {
  const sum = paymentsForBatch.reduce((total, p) => total + p.amount, 0);
  await dbService.updateRecord(batch.dbPath, { totalPaid: roundNaira(sum) });
  return roundNaira(sum);
}
